- app.py
- scraper.py
Hi Logan,
I have noticed the county name format has been changed in the original json file. So we need to follow that to make it work the script. 
Can you confirm the change and merge it?
Thanks,
Kengo
> Fixed county name format change to follow the original data.

- dataSF_scraper.py
A list of methods that fetch data from the following sources. The methods return python Dictionaries. There are methods to get the tables in their entirety, as well as methods that return data grouped by major groups. Data are the following:
1. [Race and Ethnicity](https://data.sfgov.org/COVID-19/COVID-19-Cases-Summarized-by-Race-and-Ethnicity/vqqm-nsqg)
2. [Age and Gender](https://data.sfgov.org/COVID-19/COVID-19-Cases-Summarized-by-Age-Group-and-Gender/sunc-2t3k)
3. [Date Transmission and Dispostion](https://data.sfgov.org/COVID-19/COVID-19-Cases-Summarized-by-Date-Transmission-and/tvq9-ec9w)
4. [Hospitalizations](https://data.sfgov.org/COVID-19/COVID-19-Hospitalizations/nxjg-bhem)
5. [Tests](https://data.sfgov.org/COVID-19/COVID-19-Tests/nfpa-mg4g)
> #15 Fetch detailed data from sf.data.gov

- dataSF_scraper.py
Total cases excludes deaths. As of today, the totals over the Transmission table are the same as the numbers being reported on the DPH website: https://www.sfdph.org/dph/alerts/coronavirus.asp
> #15 Add total cases and deaths by summing over the transmission table.

- news/alameda.py
- news/base.py
- news/utils.py
- scraper_news.py
You can now get a news feed for Alameda county with:
```console
> python scraper_news.py alameda
```
This also fixes an issue with the default value for format. (You had to explicitly specify a format; the default was getting misinterpreted.)
> Scrape Alameda News

- news/__init__.py
- news/contra_costa.py
This depends on #70 and fixes #63.
> Add news scraper for Contra Costa County

- news/__init__.py
- news/napa.py
This depends on #72 and fixes #62. The only files with changes from #70 are `news/__init__.py` and `news/napa.py`.
> Add news scraper for Napa County

- covid19_sfbayarea/news/__init__.py
- covid19_sfbayarea/news/napa.py
- covid19_sfbayarea/news/solano.py
- covid19_sfbayarea/news/utils.py
This depends on #72 and fixes #61. The only files with changes from #70 are `news/__init__.py` and `news/solano.py`.
> Add news scraper for Solano County

- covid19_sfbayarea/news/__init__.py
- covid19_sfbayarea/news/sonoma.py
This depends on #72 and fixes #67. The only files with changes from #70 are `news/__init__.py` and `news/sonoma.py`.
> Add news scraper for Sonoma County

- covid19_sfbayarea/data/sonoma.py
This is the last PR made on a new Git branch
> Sonoma race fix

- scraper.py
Corona Data Scraper changed the format of US to United States. We only have to follow them.
> Changed 'US' to 'United States' in CDS scraper

- covid19_sfbayarea/news/contra_costa.py
Contra Costa changed the format of its news page slightly, making the table of contents entries into headers and switching to a structure so every two months share a single parent `<div>`. For example:
<div>
<h3>September 2020</h3>
<ul>[news items in here]</ul>
<h3>August 2020</h3>
<ul>[news items in here]</ul>
</div>
Previously, there was one `<div>` that wrapped each heading + news list pair.
Fixes #123.
> Fix repeated news entries for Contra Costa county

- covid19_sfbayarea/news/alameda.py
The news scraper is currently failing for Alameda: https://github.com/sfbrigade/stop-covid19-sfbayarea/runs/1105106953?check_suite_focus=true
Previously, we only saw `<br>` elements on the Alameda news page as delimiters between the title and summary of a news item, or double `<br>`s as delimiters between news items. Now they're all over the place, including between the date and title. Since we previously assumed the `<br>` must be separating the title and summary, that meant we kicked into summary parsing mode without ever reading any title data. Luckily, that would cause the scraper to fail rather than output bad data (all news items MUST have titles), but that still means the scraper was broken.
The new approach here is to check to see whether we've gathered any title data yet when we …
> HOTFIX: Alameda news page now has more `<br>`

- README.md
Adds PR review guidelines to the README.
> REVIEW REQUIRED: Add PR review guidelines to README.md

- covid19_sfbayarea/data/solano.py
To run the scraper:
`$ python3 scraper_data.py solano`
Here is the main county dashboard: https://doitgis.maps.arcgis.com/apps/MapSeries/index.html?appid=055f81e9fe154da5860257e3f2489d67
Here is the output I received on Friday Sept 19:
https://gist.github.com/elaguerta/0be07f9b23af224ea882b88676866fa4
> Fix Solano data scraper

- covid19_sfbayarea/news/alameda.py
Alameda news items used to follow a pretty standard pattern where none of the components are contained in other elements. It typically looked like:
```html
<strong>Date</strong> <a href="...">Title</a>
```
But now some parts of some news items are getting wrapped in `div` elements, causing us to have trouble iterating through all the parts and extracting the complete data. For example, a news item on the page now looks like this:
```html
<div><strong>Date</strong></div> <a href="...">Title</a>
```
Note this isn't really consistent across news items, so it's all pretty messy. In any event, the new structure causes a couple problems that get worked around in this change:
1. We have to find a containing element that we don't look beyond for news content (otherwise we might include other text …
> HOTFIX: Handle Alameda news with more nested nodes

- covid19_sfbayarea/data/marin.py
The Marin scraper has been failing for a while — it turns out they separated cases and deaths into different charts/tables. This is pretty much the minimum fix to get it running.
Fixes #146.
You can test this by running the Marin data scraper and making sure it outputs actual data instead of an error message:
```sh
$ python scraper_data.py marin
```
> HOTFIX: Separate tables for cases and deaths

- covid19_sfbayarea/news/san_francisco.py
> Add summary to San Francisco NewsItem

- covid19_sfbayarea/news/santa_clara.py
> Scrape Santa Clara news from multiple calendar years

- covid19_sfbayarea/news/san_francisco.py
The SF news page markup no longer surrounds the summary/abstract text in an element, and the scraper was failing when trying to find it with errors like:
```
San Francisco county failed: 'NoneType' object has no attribute 'get_text'
Traceback (most recent call last):
File "/home/runner/work/stop-covid19-sfbayarea/stop-covid19-sfbayarea/scraper/scraper_news.py", line 82, in main
run_county_news(county, from_, format, output)
File "/home/runner/work/stop-covid19-sfbayarea/stop-covid19-sfbayarea/scraper/scraper_news.py", line 39, in run_county_news
feed = news.scrapers[county].get_news(from_date=from_)
File "/home/runner/work/stop-covid19-sfbayarea/stop-covid19-sfbayarea/scraper/covid19_sfbayarea/news/base.py", line 80, in get_news
return instance.scrape()
File …
```
> HOTFIX: SF news no longer has markup for a summary

- covid19_sfbayarea/news/contra_costa.py
The Contra Costa County news page uses Wix, and recently it's started blocking our scraper entirely by returning a blank page with JS that loads all the content. We can fix this by setting a `User-Agent` header from a browser, but a more robust long-term solution (in case they do something more complex) is to just use Selenium. That's what I've done here.
Fixes #193.
> HOTFIX: Use Selenium to load Contra Costa news

- covid19_sfbayarea/news/santa_clara.py
Santa Clara's news page now uses a table to display news items, and is set up with totally different class names. This rejiggers our selectors to handle the new design, and adds slightly more informative error messaging while we're at it.
To test: just run the news scraper and make sure it outputs news data and doesn’t end with an error.
```sh
$ python scraper_news.py santa_clara
```
> HOTFIX: Handle redesigned Santa Clara news page
