sfbrigade/data-covid19-sfbayarea

- data/covid_19_santa_clara.csv
This dataset looks a bit incomplete because most of the columns are missing time updates. The Santa Clara Public Health Dept only started publishing that on the 15th.
> Add Santa Clara dataset

- .editorconfig
- .gitignore
- requirements.txt
- run_scraper_news.sh
- scraper_news.py
It turns out San Francisco (and all the other bay area counties I've checked so far) don't actually have RSS or other feeds for news, so we need to start scraping these sites if we want to show news across all the counties. This commit adds a really basic scraper that reproduces the current data format used by the site and scrapes San Francisco's coronavirus news page (the site only shows San Francisco right now, so we aren't losing anything here).
You can run it with `sh run_scraper_news.sh` or `python scraper_news.py`.
I didn’t add any tests since there’s no existing structure for them, but let me know if you want me to pull in pytest or something.
> Add basic news scraper for San Francisco

- .gitignore
- news/__init__.py
- news/alameda.py
- news/base.py
- news/san_francisco.py
- news/utils.py
- scraper_news.py
In order to make a big set of scrapers more manageable, this creates a `news` package where we can have one module per scraper (plus other support modules). The same script as before is the entry point, but you specify counties as arguments, e.g:
```sh
> python3 scraper_news.py san_francisco
> python3 scraper_news.py alameda
> python3 scraper_news.py san_francisco alameda
```
If you don't specify any arguments it currently defaults to `san_francisco`, but in the future this will eventually be turned into a combined feed of all counties instead.
~Before merging, I want to clean up the argument parsing by using either `click` or `ArgParse`, but this should otherwise be good to go.~ *(This is done now.)*
Fixes #41.
> Restructure news scrapers into `news` package

- CDM_README.md
- all_age_brackets_template.json
- data-model.json
- sf_generic_cdm.js
- sf_generic_cdm.json
Hi folks! @elaguerta @kengo-sony @ldtcooper @Mr0grog, @frhino, @collincr, @VincentLa14
Here's a common data model I created for the parsing of just the SF json files (and not the dashboard itself). I then added data points to be parsed that are only present on the dashboard, and I commented those out. I made the distinction since I wasn't sure if the dashboard itself would be scraped.
(Interesting side note - there is data that is in the dashboard that is not in the linked source data i.e. Native American on the race/ethnicity graph)
Some things to mention here:
- Under testing, it made sense to me to keep `pos` and `pct` along with the time series data and not as values associated with a "tabulation" key (like gender/age for cases/deaths) since pos/pct were visualized on a time series …
> Requesting Review of SF Common Data Model

- news/base.py
- news/feed.py
- news/san_francisco.py
- requirements.txt
- scraper_news.py
You can now specify the output format for the news scraper with the `--format` option, which can be:
- `json_simple` (default) the current format
- `json_feed` the JSONFeed standard (https://jsonfeed.org/version/1)
- `rss` for RSS 2.0
Eventually, we'll switch `json_feed` to be the default, but for now we need to not break existing automation.
This uses dataclasses for some of its work, which are new in Python 3.7. I think that’s our minimum version, so this should be OK. (Is that right, @ldtcooper?)
You can also specify more than one format, and specify an output directory. That way, a command like this:
```sh
$ python scraper_news.py san_francisco alameda --format json_feed --format rss --output feed_data
```
Can write out 4 files, which would be a pain to deal with on STDOUT:
- …
> Support json_feed, json_simple, and rss news formats

- data_scrapers/__init__.py
- data_scrapers/alameda_county.py
- run_scraper_data.sh
- scraper_data.py
Add `scraper_data.py` and `run_scraper_data.sh` to mirror the news side. 
A few high-level questions:
1. `scraper_data.py` writes a file `data.json` in the main repo. Where should this file live? Should I add it to .gitignore?
2. Should we modify the `run_scraper_data.sh` script to accept command line arguments (specific counties)?
3. The news scraper has its own base class. Should I set up a parallel class for the data scrapers? The counties all seem like snowflakes. The only common method I would enforce for each scraper is`get_county()`, returning the top-level .json for that county
> #46 Add CLI to run data scrapers

- app.py
- data_scrapers/san_francisco_county.py
- setup.cfg
Per a discussion in Slack, we should be a little bit more strict about requiring and checking type annotations. This adds a config file for Mypy and specifies a configuration that is more strict. It should help us be a little better about our types.
This required some updates to existing files, and will probably require changes to any in-progress PRs, so those will need to be rebased or updated once this lands.
> Add more strict configuration for Mypy

- news/__init__.py
- news/alameda.py
- news/feed.py
- news/santa_clara.py
- news/utils.py
Unfortunately, the page we're scraping gets populated at runtime via JavaScript, so, like Alameda, I wound up using Selenium. This also fixes missing support for tags in our RSS output (the news items here have “categories,” like “press release” or “announcement,” and this code sets those as tags on each news item).
Note this conflicts with #69 (like pretty much everything will), so whichever PR merges first will require fixes in the other PR before we can merge it.
Fixes #64.
> Add news scraper for Santa Clara County

- news/__init__.py
- news/san_mateo.py
This depends on #72 and fixes #65. The only files with changes from #70 are `news/__init__.py` and `news/san_mateo.py`.
> Add news scraper for San Mateo County

- covid19_sfbayarea/news/contra_costa.py
I must have either missed this or had a merge/rebase error when I moved all the files around.
> Fix variable name typo in Contra Costa news

- covid19_sfbayarea/news/contra_costa.py
- covid19_sfbayarea/news/utils.py
I noticed a couple issues in the [Contra Costa news scraper's updates](https://github.com/sfbrigade/stop-covid19-sfbayarea/pull/186/files) today:
1. Some titles had “| Spanish” at the end because some news items have alternate language versions, and we weren’t pulling those out from the title. (The links were still fine.)
2. Some dates on the page have typos that caused them to get parsed poorly. 😞 
This fixes both of those.
> Clean up language and date issues in Contra Costa News

- install.sh
- run_scraper.sh
- run_scraper_data.sh
- run_scraper_news.sh
Back in #54, @rickpr made the `.sh` scripts and top-level `.py` scripts in this project executable. However, the bash scripts don't have a shebang line describing what interpreter should be used. Thankfully, most systems default to bash in this case, so everything usually works OK -- but that's no guarantee. This makes things a little safer by adding a shebang line specifying that bash should be used.
(Inspired by the small mess I ran into in #89.)
> Add shebang line to executable bash scripts

- .circleci/config.yml
- README.md
- covid19_sfbayarea/news/feed.py
- covid19_sfbayarea/news/utils.py
- requirements-dev.txt
- tests/news/feed_test.py
In situations where multiple feed items have the same publish time (usually because the county only specifies the date and not the time), we sometimes wind up with feed items getting a slightly different order between scraper runs. We now use the ID of the news items as an additional sort criteria to make sure they stay in the same order.
This change also adds some actual tests!
Fixes #88.
> Ensure reliable order for items in news feeds

- scraper_news.py
If you didn't specify any county names to scrape, the news scraper used to only output news for San Francisco. It now outputs news for all counties instead, which is a more sensible default and matches up with the data side. (Code that depended on the old default has now all been fixed, so this change is finally safe.)
While we’re at it, this also updates the default format from simple JSON to JSON feed.
Fixes #92.
> Default to *all* counties for news scraper CLI

- covid19_sfbayarea/data/hospitals.py
- data_models/README.md
- data_models/hospitals_data_model.json
- tests/data/test_hospitals.py
This is a PR to add a script to fetch hospitalization data from the data.ca.gov API, raised in issue # 29. I've tried to keep the output model as consistent as possible with the existing model, although there are necessarily some differences. I've also added some documentation of the output model in the README. I included logging for easier debugging/transparency, but that can be removed for consistency. Let me know if you spot bugs or other issues.
> Issue #29: Get CA COVID-19 Hospital Data

- .circleci/config.yml
- scraper.py
CDS updated their data format to be an array of objects (instead of a dict where each area is identified by name) and slightly changed the names/identifiers for counties. This updates the scraper to work with the new format.
> Update CDS scraper to handle new data format

- covid19_sfbayarea/news/feed.py
- scraper_news.py
Standardize news serializers by making sure they all have the same signature (they take a `pretty` option and return bytes). This also changes them from returning strings to returning bytes so that we can add things like XML encoding directives (e.g. `<?xml version='1.0' encoding='utf-8'?>`) where relevant. (RSS recommends including one, for example.)
Fixes #93.
> Give all news serializers the same signature

- README.md
- covid19_sfbayarea/news/base.py
- covid19_sfbayarea/news/san_mateo.py
- scraper_data.py
- scraper_news.py
Use the new `--from` CLI argument to set a timeframe for news. It can be a date after which news items should be included OR a number of days before the current time:
```sh
$ python scraper_news.py --from 2020-06-05
$ python scraper_news.py --from 7
```
The default is "31" -- i.e. the past month.
Fixes #43.
> Limit news scrapers to a given timeframe

- scraper_news.py
Back in #95, I started making all the news serializers output bytes instead of strings. However, we still used `print()` to output the results on STDOUT, and in Python 3, `print()` no longer handles bytes like strings. That made our STDOUT output no longer parseable as JSON (or RSS, or whatever). (I missed this because we always output to files instead of STDOUT in production.) Click's `echo()` function supports bytes, so use that instead.
> Output news results to STDOUT correctly

- covid19_sfbayarea/news/base.py
- covid19_sfbayarea/news/solano.py
- covid19_sfbayarea/news/utils.py
The main news page for Solano County presents only a limited number of items, and doesn't give us enough to actually cover the full time range we're looking for in a lot of cases. Instead of loading and parsing the main news page, we now load the same endpoint that is used to display the county's full news archives.
NOTE: this required some changes to response body decoding since the endpoint does not specify the encoding it uses. I had to add a way to set a hard-coded fallback encoding when one cannot be inferred from the HTTP response.
> Load more news from Solano via fancy XHR endpoint

- covid19_sfbayarea/news/alameda.py
- scraper_news.py
Alameda county redesigned their COVID-19 site, moving news to a different URL and changing the HTML layout of the page. This updates the news scraper to handle the new format, which is a little more complicated to parse. (On the upside, it no longer requires Selenium.)
> Update Alameda news scraper to handle new HTML

- Dockerfile
- README.md
- run_docker.sh
Since it can be tough to get all the pieces installed and working right when using WSL on Windows, this dockerfile provides a way to develop and run the app in a container with all the necessary dependencies. You can build an image from it with:
$ docker build -t data-covid19-sfbayarea .
And then run it via:
$ docker run -it data-covid19-sfbayarea
$ docker run -it data-covid19-sfbayarea python scraper_data.py --more args --here
@ldtcooper does this work for you? It might be better to test with the news scraper, since it seems like some of the data scrapers are broken at the moment.
> Add Dockerfile that works for development use

- covid19_sfbayarea/utils.py
- scraper_data.py
- scraper_news.py
This ports the changes to the data scrapers from #118 over to the news scrapers, adds slightly nicer formatting, and includes a stack trace. The main thing is that an exception in any scraper does not stop the others from completing. Output-wise, if the Alameda scraper failed, you'd see something like:
I added the stack trace in because it seemed like that would be pretty useful information most of the time, but we could also:
- Only show it for errors that aren’t `FutureWarning` or `FormatError` (on the assumption that those errors were expected and are easy to track down, while others are a surprise and the stack would be doubly helpful).
- Add a CLI option to show it, e.g. `--verbose` or `--trace-errors`.
- Add an environment variable to show it, e.g. `TRACE_ERRORS=true`.
- Just strip …
> Let news scrapers fail independently

- covid19_sfbayarea/news/solano.py
- covid19_sfbayarea/news/utils.py
We previously used `element.get_text(strip=True)` when extracting text for Solano news, but that causes real issues when there are child elements (links, bold, etc.) mixed in, because it strips each bit of text independently, leaving us with no spaces at all between words that are at the edge of elements. This handles the whitespace a little better, and more like it normally gets handled in HTML.
Fixes #96.
> Handle stripping whitespace better in Solano news

- .circleci/config.yml
- README.md
- covid19_sfbayarea/data/marin.py
- covid19_sfbayarea/data/san_mateo/cases_by_age.py
- covid19_sfbayarea/data/san_mateo/cases_by_gender.py
- covid19_sfbayarea/data/san_mateo/deaths_by_age.py
- covid19_sfbayarea/data/san_mateo/deaths_by_gender.py
- covid19_sfbayarea/data/sonoma.py
- requirements-dev.txt
- tests/data/test_valid_output.py
It turns out several of our scrapers don't quite conform to the data model. We should probably have some classes that model the data and can enforce some formatting and validation, but it's also good to test that the final result adheres to a schema, which is what this does.
Because it's tough to mock responses in Selenium, these tests run against live county websites right now. That can make them pretty slow or intense to run, so this class of tests is disabled by default and you have to opt-in to run them (in CI, we opt-in). To do so, set the `LIVE_TESTS` environment variable to `*` to run all live tests, or set it to a comma-separated list of county names to run just those counties:
$ LIVE_TESTS='*' python -m pytest -v .
$ LIVE_TESTS='san_francisco,sonoma' python -m pytest -v . …
> Add tests to validate output format

- scraper.py
Workaround for #132. Seems the CDS public site is currently busted, but the data is still updating and available directly from s3 (https://liproduction-reportsbucket-bhk8fnhv1s76.s3-us-west-1.amazonaws.com/v1/latest/timeseries-byLocation.json)
Not the prettiest URL ... but it works! At least we can keep our site being updated.
> workaround to update the CDS data.

- covid19_sfbayarea/news/san_mateo.py
- tests/news/san_mateo_test.py
Fixes #134.
Many news items have their title prefixed with a date in San Mateo, which can be a bit confusing and redundant, especially when we normally display the date right before the title at https://panda.baybrigades.org.
To alleviate this, we attempt to remove the date at the start of the title. However, the county recently changed its date format to include abbreviations, which we didn't previously account for. It also turns out that dates are getting formatted differently in Spanish (Chinese articles seem to have no date prefix, and I don't have examples of any other languages to test).
Additionally, it turns out news items with summaries have a similar date prefix on the summary, too! We now remove it as well.
Finally, I added some tests for the San Mateo scraper here. Obviously …
> Fix date prefix removal in San Mateo news

- covid19_sfbayarea/news/contra_costa.py
The Contra Costa county news page occasionally returns en empty page with no news content, resulting in bad PRs like this one: https://github.com/sfbrigade/stop-covid19-sfbayarea/pull/421
This doesn't solve the core problem with Contra Costa's page, but it raises an error if there's no news, which will result in output for other counties and no changes to Contra Costa. A failure with notification is much better than bad output.
🚨 ~**This depends on sfbrigade/stop-covid19-sfbayarea#426 so that the workflow running this scraper only fails if _all_ scrapers fail.** This is similar to [the data v2 workflow](https://github.com/sfbrigade/stop-covid19-sfbayarea/blob/dd3f5d55e570ed7c7d0c3366cd59d537eca7bf1e/.github/workflows/data_update_v2.yml#L62-L68).~ 🚨 (Update: the updates needed on the …
> Raise an error if there's no news in Contra Costa

- README.md
- covid19_sfbayarea/data/hospitals.py
This PR adds information on how to use `run_scraper_hospital.sh` in the README. I also removed some outdated info from a comment line in `hospitals.py`, and took the liberty of updating the link to the Bay Area Pandemic Dashboard in the README as well.
> Update README with info on hospitalization data scraper

- covid19_sfbayarea/news/contra_costa.py
In this recent news update, you’ll notice that all the Contra Costa news from this month just disappeared: https://github.com/sfbrigade/stop-covid19-sfbayarea/pull/442/files
We already had some relatively complex space matching in some parts of Contra Costa regular expressions, but now they have dropped other complex space characters in new places that is causing the scraper to miss entire months' worth of news. To handle it, I’ve basically just made our headings and title matchers accept the more complex space character set anywhere they were previously using `\s`. 😩
You can test this by running:
```sh
$ ./run_scraper_news.sh contra_costa
$ python scraper_news.py contra_costa
```
And make sure there are news items for September, and that the titles of most news items generally seem …
> HOTFIX: Allow special spaces in more Contra Costa strings

- covid19_sfbayarea/news/alameda.py
- tests/news/alameda_test.py
The Alameda news page now has links that take up only part of the title. The parser sometimes identifies these as links to language-specific versions of the news item, which causes it to stop parsing the title and start looking for language links. However, these links aren't language links, and we need to continue parsing the title as we move through them.
For example, the Alameda news page currently has this entry:
…which was causing us to output the title:
> Guidance on How to Celebrate Halloween and D
…instead of:
> Guidance on How to Celebrate Halloween and Día de los Muertos Safely
This fixes the issue by being *much* more specific about what we expect for the text of a language link. This may have issues if there are ever typos in the language names, but seems to work well enough. …
> HOTFIX: Handle messy links in Alameda news titles

- covid19_sfbayarea/news/contra_costa.py
- tests/news/contra_costa_test.py
Contra Costa's news page now sometimes shows Spanish translations of news items in a new format (some items also use the old format). Items in the new format contain additional text beyond the main news heading, causing us to fail to extract news data from them (and therefore skip them as if they were not news items).
The actual change here is just a one-liner. The rest is adding tests. :)
Fixes #142.
You should be able to test this by making sure the news items described in #142 are correctly showing up in the resulting output when you run:
```sh
$ python scraper_news.py contra_costa
```
You can also just compare the output to the actual [Contra Costa News Page](https://www.coronavirus.cchealth.org/health-services-updates) and make sure all the items are listed and formatted correctly.
> HOTFIX: Handle new Contra Costa translation format

- covid19_sfbayarea/news/sonoma.py
Some of the HTML elements we transform into tags for news items in Sonoma County have line breaks in them, and they weren't being handled well. We already have tools for doing this better, but we just weren't using them. This switches over to them.
For example, in this PR: https://github.com/sfbrigade/stop-covid19-sfbayarea/pull/497
We have a news item like:
```js
{
"title": "COVID-19 Rental Assistance\u00a0For Sonoma County Renters and Landlords",
"date_published": "2020-10-14T00:00:00-07:00",
...
"tags": [
"Sonoma CountyCommunity Development Commission"
]
}
```
But it should really be:
```js
{
"title": "COVID-19 Rental Assistance\u00a0For Sonoma County Renters and Landlords",
"date_published": "2020-10-14T00:00:00-07:00",
...
"tags": [
"Sonoma County Community Development Commission"
] …
```
> Sonoma news: handle whitespace in tags correctly

- covid19_sfbayarea/news/feed.py
- tests/news/feed_test.py
Napa county's website is currently repeating each news item 33 times (!), so we are, too:
While this isn't necessarily our fault, we could easily handle this by deduping news items when we add them to the feed.
You can test this by running:
```sh
$ ./run_scraper_news.sh napa
$ python scraper_news.py napa
```
And making sure each item in the output is only shown once.
> HOTFIX: Ensure news items are unique

- covid19_sfbayarea/data/alameda/cases_by_age.py
- covid19_sfbayarea/data/alameda/deaths_by_age.py
Per conversation with the team, we don't want to hide the Unknown Age. We already show this for San Mateo County, we should do it here too.
Closes https://github.com/sfbrigade/data-covid19-sfbayarea/issues/147
> Do capture unknown age for Alameda

- covid19_sfbayarea/data/sonoma.py
The scraper is currently failing because Sonoma County changed how they categorize races/ethnicities (there are more groups, and the naming has changed slightly even for groups that are mostly the same). This also fixes a bug where the error message about this situation was incorrectly formatted.
Fixes #154.
NOTE: this PR was extracted from #155 (it’s the must-merge-now/hotfix portions of that change). **I’m merging it immediately since it’s effectively been sitting awaiting review for several days** — well past our required review window for hotfixes.
> HOTFIX: Update race/ethnicity groups in Sonoma

- covid19_sfbayarea/data/sonoma.py
Sonoma county recently added a new race/ethnicity group ("Other, non-Hispanic"), so its scraper needs to be updated to account for it.
**To Test:**
Run `python scraper_data.py sonoma` and make sure it outputs data instead of an error.
> HOTFIX: Add "Other, non-Hispanic" race to Sonoma

- covid19_sfbayarea/data/marin.py
While working on #152, I noticed that the Marin scraper makes approximately 1 bajillion requests to the same URL (the Marin dashboard web page) — it generally starts a new web browser and then loads a clean copy of the page for each area that it wants to parse. That makes the scraper a little slow, but more importantly, puts us at risk of getting banned or rate limited if Marin ever adds spam/DOS prevention security tools to their site.
That can obviously be a little more efficient, so I went ahead and tried to slim that down by passing a webdriver instance around instead of just a URL. I probably went a bit overboard by wrapping the webdriver code in `MarinDashboardPage` class that does all the more abstract stuff like extracting and parsing chart data. I didn’t really change method …
> Stop reloading the Marin dashboard repeatedly while parsing it

- covid19_sfbayarea/data/sonoma.py
- covid19_sfbayarea/utils.py
~This fixes #154, where the race/ethnicity groups in Sonoma County have been changed.~
It also adds a new tool for ensuring actual and expected group names are the same in all the zillion places we do this across the data scrapers, so we get better info. Instead of an error like:
```
FormatError: The racial group Asian, non-Hispanic is new in the data -- please adjust the scraper accordingly
```
We now get:
```
FormatError: Racial groups are different -- removed: {'Multi-Race', 'Asian / Pacific Islander, non-Hispanic', 'Other', 'Black / African American, non-Hispanic'}, added: {'Asian, non-Hispanic', 'Black/African American, non-Hispanic', 'Native Hawaiian and other Pacific Islander, non-Hispanic', 'American Indian/Alaska Native, non-Hispanic', 'Multi-racial, non-Hispanic'}
```
So you can …
> Improve error messaging for changed keys in Sonoma County

- covid19_sfbayarea/data/alameda/power_bi_querier.py
- covid19_sfbayarea/data/marin.py
- covid19_sfbayarea/data/san_francisco.py
- covid19_sfbayarea/data/san_mateo/power_bi_querier.py
- covid19_sfbayarea/data/san_mateo/time_series_cumulative.py
- covid19_sfbayarea/data/san_mateo/time_series_daily.py
- covid19_sfbayarea/errors.py
- covid19_sfbayarea/utils.py
- tests/news/san_mateo_test.py
It turns out the scrapers have been failing for a while because of a stray `print()` call, and that failure masked a series of other, further failures from a variety of counties. This attempts to fix them all:
- Clean up a couple stray `print()` calls (this should be all of them). One should not have existed at all, and the other I’ve replaced with a more detailed exception that I think actually does the job better.
- Clean up what appears to be unintentional spaces in Marin county’s table headers.
- Support new genders in San Francisco’s data.
- Support new age groups in San Francisco’s data, and also switch to human-friendly, county defined age groups (we decided to do this for all counties a while back, and this error seemed like a good time to go ahead and do it for SF rather then …
> HOTFIX: Clean up a variety of errors in data scrapers

- covid19_sfbayarea/data/alameda/time_series_tests_percent.py
For some days in Alameda, we get strings instead of numbers in the percent positive tests timeseries. This fix is not particularly generic, but solves the immediate problem. It looks like PowerBI may try to preserve precision by sending strings when float64 cannot accurately represent a value. We'll have to think about more generic ways to account for this.
Example excerpt from the data:
```json
{
"results": [
{
"result": {
"data": {
"dsr": {
"DS": [
{
"PH": [
{
"DM0": [
{"C": [1607644800000, 6.916541]},
{"C": [1607731200000, 7.157232]},
{"C": [1607817600000, "7.2322939999999996"]},  // Not a number!
{"C": [1607904000000, 7.288172]},
{"C": [1607990400000, 7.475967]}
> HOTFIX: Handle strings in Alameda %-positive tests

- covid19_sfbayarea/data/solano.py
The last day of Solano's data seems to be getting repeated in their dataset (every row is repeated once, totally verbatim, as far as I can tell). I'm not sure why that's happening (it's there that way in the source data if you go look on the web), but it seems benign, so I've just added a fix here to de-duplicate the age groups (we just take the last value we have for each group). This already happens naturally for race/ethnicity and gender (since we build dicts instead of lists), so there's no need to fix those.
> HOTFIX: handle repeat rows in Solano age groups

- covid19_sfbayarea/news/solano.py
We had some code meant to remove non-useful prefixes on the news summaries from Solano county, but most news items are still coming through with a dash in front anyway:
{
"summary": "— Starting Thursday, December 17, 2020 at 11:59 p.m., Solano County will…"
}
This fixes the regex we use to elimite it:
{
"summary": "Starting Thursday, December 17, 2020 at 11:59 p.m., Solano County will…"
}
> Drop dashes at start of Solano news item summaries

- covid19_sfbayarea/data/__init__.py
- covid19_sfbayarea/data/santa_clara.py
At some point between the original issue and now, Santa Clara added all the data behind their dashboard to a Socrata data portal, making it much easier to load based on @elaguerta’s earlier work.
Some items to note here:
- There’s no demographic data for tests. (Or at least I couldn’t find it.)
- There’s a new transmission category here we haven’t had in other counties: `outbreak_associated`. This means the case was related to an outbreak at a particular location (e.g. a factory) or event. More details in the "meta".
- Santa Clara does not differentiate community spread and unknown transmission, so these both get categorized as `unknown` and `community` gets a value of `-1`.
Fixes #28.
> Add data scraper for Santa Clara

- covid19_sfbayarea/data/marin.py
- covid19_sfbayarea/data/utils.py
Marin now publishes COVID data in an actual data portal with a real API and changed the dashboard to use Tableau. That broke our scraper (because all the charts are now built in an entirely different way). The best way to fix was to rewrite on top of the Socrata data portal API, which we should happily expect to be much more stable.
This also adds caching to the Socrata API so we can make multiple calls to the same URL without actually making multiple HTTP requests. The Marin data is arranged such that a lot of different dimensions of data are combined (unlike most other portals where they are separated), and caching lets us keep the logic straightforward without making unnecessary repeated requests.
This also turns out to fix #162 -- unknowns are now included in the data!
Fixes #165.
> HOTFIX: Rewrite Marin data scraper to use Socrata

- covid19_sfbayarea/news/napa.py
Napa county's page for all news is broken (`https://www.countyofnapa.org/CivicAlerts.aspx?sort=date`) and doesn't load, so we can't actually scrape it. However, if we look at news from only a subset of categories, it works fine (it appears that category 17 [Board of Supervisors] is broken). This lists all the categories except one that breaks, so the page loads and gives us most news.
Test this by running:
```sh
$ python scraper_news.py napa
```
And making sure it outputs some news instead of an error.
> HOTFIX: Napa all news page is broken

- covid19_sfbayarea/data/__init__.py
- covid19_sfbayarea/data/arcgis.py
- covid19_sfbayarea/data/napa.py
This adds data support for Napa County (wow, that was a long time coming). It's mostly based on the ArcGIS feature server identified by @1ec5, which lists *every case* in Napa County.
There are a few questionable bits I’d love feedback on here:
1. All cases have a date for when the test results were received, but a few do not have a date for when the test was *taken*. The county works around this by showing cases by test result received date, while @1ec5 worked around it for Wikimedia Commons by doing the same thing I’m doing here: using the test taken date where available, and the test received date otherwise. I think this makes the most sense, but it will make our numbers differ slightly from the county dashboard’s display.
- See the Wikimedia Commons data at: …
> Add Napa County data scraper

- covid19_sfbayarea/data/sonoma.py
- tests/data/test_valid_output.py
This is a hotfix to handle the changes to Sonoma County's "Coronavirus Cases" page, and specifically to its "Cases by Source" table. It appears that table has been replaced by a table called "Proportion of Cases Attributable to Specific Exposure Locations," and that instead of raw case counts, several percentage figures are given for active cases, cases within a given time frame ("30-44 Days Ago"), and all time. The descriptions of the transmission settings (e.g. "Workplace") have also changed and become more granular.
In this batch of changes, I'm erring on the side of capturing the new granularity rather than on consistency with our prior categories, since the more granular data may be more helpful/informational. I've also made the call to only grab the percentage figure for "All Time" …
> Fix sonoma data (#178)

- covid19_sfbayarea/ca_counties.py
It turns out our list of California counties was not complete! I noticed this while working on https://github.com/Mr0grog/ca-covid-vaccination-stats this afternoon.
> Add missing counties to couny list

- covid19_sfbayarea/data/__init__.py
- covid19_sfbayarea/data/contra_costa.py
- covid19_sfbayarea/data/qlik.py
- requirements.txt
There are quite a few complexities and caveats with this one:
- Positive test counts are estimated based on rate (since the county only publishes the rate), similar to Santa Clara.
- Daily test counts, total test counts, and test positivity rates are each separate charts that cover different date ranges! Putting them together as a single series is a bit messy. Worse, daily test counts and totals don't completely agree (the total tests series starts earlier, and roughly the first two weeks of daily tests have `0` for the value, while the difference between total tests on those days is often > 0). After March 18, 2020 they mostly agree, so daily total test counts seems like the better source. I've calculated daily tests based on the difference between days in total tests, rather than using …
> Add data scraper for Contra Costa County

- covid19_sfbayarea/data/san_mateo/time_series_tests.py
It looks like someone renamed the table and columns for test data in San Mateo, which broke the scraper. I've updated with the new names and verified that the data looks at least *roughly* like it used to. (It seems the timeseries now starts a month later than it used to, though. I tried using a `Where` clause to extend it, but no dice. This is just all that's there now.)
This fixes the broken scrapes we are currently experiencing for San Mateo, e.g. https://sfbrigade.slack.com/archives/C01AV92EM47/p1615198414000100
> HOTFIX: San Mateo tests table was renamed

- covid19_sfbayarea/data/san_mateo/__init__.py
San Mateo County does not provide a timeseries of deaths, so we previously used the state's data portal for that data. The state dataset we were pulling from has been deprecated in favor of one provided by CHHS, and this updates the scraper to use that. Unfortunately, the totals it provides no longer match up with the county's provided totals, but I'm not sure what to do about that at this point other than list it in the `meta` section. 😞
The old dataset was at: https://data.ca.gov/dataset/covid-19-cases
Fixes #186.
> HOTFIX: use new CHHS dataset for San Mateo deaths

- covid19_sfbayarea/data/hospitals.py
Per [data.ca.gov](https://data.ca.gov/dataset/covid-19-hospital-data#), that CKAN resource has been deprecated and replaced by one provided by CHHS. The values and the structure appear to be mostly the same, so this hotfix mainly just points our code to the new resource.
One note: It looks like the CHHS resource doesn't return as much meta data about each of the fields as the prior CA.gov resource. Here's what the raw data looks like for the `fields` key:
```javascript
"fields": [
{"type": "int", "id": "_id"}, 
{"type": "text", "id": "county"}, 
{"type": "text", "id": "todays_date"},
{"type": "text", "id": "hospitalized_covid_confirmed_patients"}, 
{"type": "text", "id": "hospitalized_suspected_covid_patients"}, 
{"type": "text", "id": "hospitalized_covid_patients"}, 
{"type": "text", …
```
> HOTFIX: Point hospitalization data scraper to new CHHS API resource

- covid19_sfbayarea/news/santa_clara.py
Santa Clara county changed its news page's pagination (it used to be by year, but now it's simply paginated every 10 items) and changed the DOM structure for news items. This updates the scraper to work again.
> HOTFIX: Santa Clara news page pagination & DOM

- covid19_sfbayarea/utils.py
- tests/utils_test.py
We often see dates from 1920 and 1921 that seem to be someone accidentally typing two digits into a four-digit date field, and the system storing it as a century earlier. Since this seems like a common issue, we can probably just autocorrect it to be a century later.
Fixes #194.
> Autocorrect dates from 1920 or 1921 to 2020 or 2021

- covid19_sfbayarea/data/san_mateo/__init__.py
The state has ceased publishing COVID-19 deaths as a timeseries, so we need to load the data from another source. LA Times's data appears to have been more consistent with the county than the data we were previously loading from CHHS, so this not only is a hotfix, but probably improves our data quality anyway.
Fixes #190.
> HOTFIX: Get San Mateo deaths by day from LA Times

- covid19_sfbayarea/news/contra_costa.py
The Contra Costa news scraper recently stopped picking up a lot of news stories because some of the month headings on the news page are no longer actual headings (instead they are a `<p>` with several nested `<span>` inside it). The new code still relies on *some* of them being properly marked up as headings, but not all. Instead of looking for the list of news items after each month heading, we find the parent elements of the headings, and look for all list items in them.
> HOTFIX: Some Contra Costa headings aren't headings

- covid19_sfbayarea/data/marin.py
- covid19_sfbayarea/data/san_francisco.py
- covid19_sfbayarea/data/santa_clara.py
- covid19_sfbayarea/data/socrata.py
- covid19_sfbayarea/data/utils.py
This is a hotfix to implement pagination when fetching data via the `resource()` method of the `SocrataApi()` class. The absence of pagination limits the number of records fetched for a given county, which is currently noticeable for Marin on the front-end.
Fixes #203
> HOTFIX: Handle pagination for SocrataApi so all data is fetched for Marin

- covid19_sfbayarea/data/solano.py
The Solano data scraper looks for disclaimer text on the dashboard, and fails if there is none. Sometime in the last few days, they appear to have removed all the disclaimers. The data was actually coming through fine otherwise.
I switched this to log a warning, but maybe this case isn’t really exceptional enough to even do that. Either way, I figure this should be fine for a hotfix.
> HOTFIX: Solano is OK if disclaimers are missing

- covid19_sfbayarea/news/contra_costa.py
The Contra Costa news page now has some list items in the list of news articles that are just paragraphs of informative text, and don't link to any kind of news release or other URL. There's not much we can do about those in a feed, so just skip over them instead of erroring.
> HOTFIX: Skip Contra Costa items with no link

- covid19_sfbayarea/news/alameda.py
- tests/news/alameda_test.py
One of the news items on the Alameda news page has a `<br>` tag inside one of the language-specific links for the news item. This is causing the parser to flip back to the summary parsing state and read the text of the link as the news item's summary. This fixes the issue by jumping to the next sibling of the language link after parsing it, rather than unnecessarily moving *inside* the link. (Usually that’s no issue, because the text inside the link doesn't cause any special behavior.)
> HOTFIX: Alameda news has language link as summary

- covid19_sfbayarea/data/sonoma.py
Sonoma County no longer provides a breakdown of cases by gender on its dashboard, or anywhere else that we can seem to find. Because that data is missing, our scraper has been failing. This set of changes disables the pieces of code that look for that gender table, and inserts a placeholder object with null values for cases by gender for the sake of consistency and compatibility. I've left most of the code in the scraper in case the county restores this table.
Fixes #213 
I've also taken this opportunity to remove the part of the code that tried to extract the latest update time from the page metadata, as that timestamp no longer seems reliable.
Fixes #205
> HOTFIX: Disable scraper functions for discontinued Sonoma gender data

- covid19_sfbayarea/data/contra_costa.py
- covid19_sfbayarea/data/qlik.py
The Contra Costa scraper is currently failing because of SSL certificate verification problems. Ignoring SSL certificate errors resolves the issue with relatively minimal fuss.
> HOTFIX: Ignore SSL Cert errors for Contra Costa

- covid19_sfbayarea/data/contra_costa.py
The Contra Costa dashboard no longer shows data that covers a complete history of cases, so the first record has a higher cumulative number of cases than just the cases on that day. We have a sanity checking/reconciliation process that checks that, which is now causing the scraper to fail. This fixes the situation by no longer trying to reconcile the daily and cumulative cases on the first day of the dataset. (This also fixes an error we encounter while trying to *report* this failure: we checked the wrong property name for the date.)
This fixes the following error we are currently [seeing in Slack](https://sfbrigade.slack.com/archives/C01AV92EM47/p1624615435000100):
```
Contra Costa county failed: 'day'
Traceback (most recent call last):
File …
```
> HOTFIX: Contra Costa no longer has full history

- covid19_sfbayarea/data/solano.py
Right now, we get this message on the #proj-covid-alerts channel every day, and it’s not actually very useful:
> None of the elements on the dashboard contain "disclaimer?" (https://doitgis.maps.arcgis.com/apps/opsdashboard/index.html#/d28335cd317a45cd84211cd290889c27)
It’s coming from Solano County scraper and isn't really signifying a problem, but it logs every night when we scrape and makes it appear as if there *is* a problem. I’ve simply removed the warning.
> Remove warning about no disclaimers in Solano

- covid19_sfbayarea/data/contra_costa.py
- covid19_sfbayarea/data/santa_clara.py
- scraper_data.py
This fixes issues that have cropped up in two counties (Santa Clara and Contra Costa) that are breaking their scrapers:
- In Contra Costa, the specifics of the issue I worked around in #217 have changed slightly -- now the first day with data is prefixed by a month of records with case counts of 0. It seems like these are probably fake, since the first day with data still exhibits the same problem that the first day used to, that its total is clearly accounting for some earlier records that are not shown in the public data we can see. The fix is basically the same, except it's no longer about the *first* day; it's about the first day with non-zero data.
- In Santa Clara, the final row has no date. Since it's only one row and will hopefully be fixed on the county's side, I've changed the …
> HOTFIX: messy data in Santa Clara and Contra Costa

- requirements.txt
The automation over in stop-covid19-sfbayarea is failing because some of our dependencies don’t work in Python 3.10 (some deprecated features were finally removed). This just updates our dependencies to something that works.
> Fix python 3.10
